//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEventStore.Persistence.Sql {
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NEventStore.Persistence.Sql.Core.Messages", typeof(Messages).GetType ().GetTypeInfo ().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding parameter named &apos;{0}&apos; to statement..
        /// </summary>
        internal static string AddingParameter {
            get {
                return ResourceManagerStub.GetString("AddingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding snapshot to stream &apos;{0}&apos; at position {1}..
        /// </summary>
        internal static string AddingSnapshot {
            get {
                return ResourceManagerStub.GetString("AddingSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to use storage after it has been disposed..
        /// </summary>
        internal static string AlreadyDisposed {
            get {
                return ResourceManagerStub.GetString("AlreadyDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to commit {0} events on stream &apos;{1}&apos; at sequence {2} in bucket &apos;{3}&apos;..
        /// </summary>
        internal static string AttemptingToCommit {
            get {
                return ResourceManagerStub.GetString("AttemptingToCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring SQL engine to auto-detect dialect..
        /// </summary>
        internal static string AutoDetectDialect {
            get {
                return ResourceManagerStub.GetString("AutoDetectDialect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection could not be created for the specified named connection..
        /// </summary>
        internal static string BadConnectionName {
            get {
                return ResourceManagerStub.GetString("BadConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The factory provided was unable to create an object to store..
        /// </summary>
        internal static string BadFactoryResult {
            get {
                return ResourceManagerStub.GetString("BadFactoryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding parameter &apos;{0}&apos; with value: {1}.
        /// </summary>
        internal static string BindingParameter {
            get {
                return ResourceManagerStub.GetString("BindingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up root threaded scope.
        /// </summary>
        internal static string CleaningRootThreadScope {
            get {
                return ResourceManagerStub.GetString("CleaningRootThreadScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command has client-controlled transaction: {0}..
        /// </summary>
        internal static string ClientControlledTransaction {
            get {
                return ResourceManagerStub.GetString("ClientControlledTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command executed, {0} rows affected..
        /// </summary>
        internal static string CommandExecuted {
            get {
                return ResourceManagerStub.GetString("CommandExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command text to be executed: {0}.
        /// </summary>
        internal static string CommandTextToExecute {
            get {
                return ResourceManagerStub.GetString("CommandTextToExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-query statement threw an exception of type &apos;{0}&apos;..
        /// </summary>
        internal static string CommandThrewException {
            get {
                return ResourceManagerStub.GetString("CommandThrewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit &apos;{0}&apos; persisted successfully..
        /// </summary>
        internal static string CommitPersisted {
            get {
                return ResourceManagerStub.GetString("CommitPersisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrent write detected..
        /// </summary>
        internal static string ConcurrentWriteDetected {
            get {
                return ResourceManagerStub.GetString("ConcurrentWriteDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring connections: master &apos;{0}&apos;..
        /// </summary>
        internal static string ConfiguringConnections {
            get {
                return ResourceManagerStub.GetString("ConfiguringConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using SQL connection factory of type &apos;{0}&apos;..
        /// </summary>
        internal static string ConnectionFactorySpecified {
            get {
                return ResourceManagerStub.GetString("ConnectionFactorySpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find connection name &apos;{0}&apos; in the configuration file..
        /// </summary>
        internal static string ConnectionNotFound {
            get {
                return ResourceManagerStub.GetString("ConnectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating command..
        /// </summary>
        internal static string CreatingCommand {
            get {
                return ResourceManagerStub.GetString("CreatingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting stream &apos;{0}&apos; from bucket &apos;{1}&apos;..
        /// </summary>
        internal static string DeletingStream {
            get {
                return ResourceManagerStub.GetString("DeletingStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserializing commit from record using serializer of type &apos;{0}&apos;..
        /// </summary>
        internal static string DeserializingCommit {
            get {
                return ResourceManagerStub.GetString("DeserializingCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserializing snapshot from data record..
        /// </summary>
        internal static string DeserializingSnapshot {
            get {
                return ResourceManagerStub.GetString("DeserializingSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering SQL dialect of type &apos;{0}&apos;..
        /// </summary>
        internal static string DialectSpecified {
            get {
                return ResourceManagerStub.GetString("DialectSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered DB provider factory settings for &apos;{0}&apos;, using &apos;{1}&apos;..
        /// </summary>
        internal static string DiscoveredConnectionProvider {
            get {
                return ResourceManagerStub.GetString("DiscoveredConnectionProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering connection settings for &apos;{0}&apos;..
        /// </summary>
        internal static string DiscoveringConnectionSettings {
            get {
                return ResourceManagerStub.GetString("DiscoveringConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing underlying thread-scoped resource..
        /// </summary>
        internal static string DisposingRootThreadScopeResources {
            get {
                return ResourceManagerStub.GetString("DisposingRootThreadScopeResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing SQL statement resources, including any transactions and connections..
        /// </summary>
        internal static string DisposingStatement {
            get {
                return ResourceManagerStub.GetString("DisposingStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing threaded scope; scope is root: {0}.
        /// </summary>
        internal static string DisposingThreadScope {
            get {
                return ResourceManagerStub.GetString("DisposingThreadScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropping tables..
        /// </summary>
        internal static string DroppingTables {
            get {
                return ResourceManagerStub.GetString("DroppingTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate commit detected; throwing..
        /// </summary>
        internal static string DuplicateCommit {
            get {
                return ResourceManagerStub.GetString("DuplicateCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerated {0} rows, re-querying for next page..
        /// </summary>
        internal static string EnumeratedRowCount {
            get {
                return ResourceManagerStub.GetString("EnumeratedRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration of paged results threw exception of type &apos;{0}&apos;..
        /// </summary>
        internal static string EnumerationThrewException {
            get {
                return ResourceManagerStub.GetString("EnumerationThrewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed statement threw an exception, but the exception was suppressed..
        /// </summary>
        internal static string ExceptionSuppressed {
            get {
                return ResourceManagerStub.GetString("ExceptionSuppressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing command..
        /// </summary>
        internal static string ExecutingCommand {
            get {
                return ResourceManagerStub.GetString("ExecutingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing query..
        /// </summary>
        internal static string ExecutingQuery {
            get {
                return ResourceManagerStub.GetString("ExecutingQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all commits for stream &apos;{0}&apos; between revisions &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string GettingAllCommitsBetween {
            get {
                return ResourceManagerStub.GetString("GettingAllCommitsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all commits from &apos;{0}&apos; forward from bucket &apos;{0}&apos;..
        /// </summary>
        internal static string GettingAllCommitsFrom {
            get {
                return ResourceManagerStub.GetString("GettingAllCommitsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all commits from Bucket &apos;{0}&apos; and checkpoint &apos;{1}&apos;..
        /// </summary>
        internal static string GettingAllCommitsFromBucketAndCheckpoint {
            get {
                return ResourceManagerStub.GetString("GettingAllCommitsFromBucketAndCheckpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all commits from checkpoint &apos;{0}&apos;..
        /// </summary>
        internal static string GettingAllCommitsFromCheckpoint {
            get {
                return ResourceManagerStub.GetString("GettingAllCommitsFromCheckpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all commits from &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string GettingAllCommitsFromTo {
            get {
                return ResourceManagerStub.GetString("GettingAllCommitsFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting snapshot for stream &apos;{0}&apos; on or before revision {1}..
        /// </summary>
        internal static string GettingRevision {
            get {
                return ResourceManagerStub.GetString("GettingRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting a list of streams to snapshot..
        /// </summary>
        internal static string GettingStreamsToSnapshot {
            get {
                return ResourceManagerStub.GetString("GettingStreamsToSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting the list of all undispatched commits..
        /// </summary>
        internal static string GettingUndispatchedCommits {
            get {
                return ResourceManagerStub.GetString("GettingUndispatchedCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing storage engine..
        /// </summary>
        internal static string InitializingStorage {
            get {
                return ResourceManagerStub.GetString("InitializingStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking commit &apos;{0}&apos; as dispatched..
        /// </summary>
        internal static string MarkingCommitAsDispatched {
            get {
                return ResourceManagerStub.GetString("MarkingCommitAsDispatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing query with max page size of {0}..
        /// </summary>
        internal static string MaxPageSize {
            get {
                return ResourceManagerStub.GetString("MaxPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the required attribute &apos;connection string&apos; on the connection name &apos;{0}&apos; in the configuration file..
        /// </summary>
        internal static string MissingConnectionString {
            get {
                return ResourceManagerStub.GetString("MissingConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the required attribute &apos;providerName&apos; on the connection name &apos;{0}&apos; in the configuration file..
        /// </summary>
        internal static string MissingProviderName {
            get {
                return ResourceManagerStub.GetString("MissingProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object has been disposed and cannot be used..
        /// </summary>
        internal static string ObjectAlreadyDisposed {
            get {
                return ResourceManagerStub.GetString("ObjectAlreadyDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open connection &apos;{0}&apos;..
        /// </summary>
        internal static string OpenFailed {
            get {
                return ResourceManagerStub.GetString("OpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening connection &apos;{0}&apos;..
        /// </summary>
        internal static string OpeningConnection {
            get {
                return ResourceManagerStub.GetString("OpeningConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening master connection &apos;{0}&apos;.
        /// </summary>
        internal static string OpeningMasterConnection {
            get {
                return ResourceManagerStub.GetString("OpeningMasterConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening new threaded scope for key &apos;{0}&apos;; scope is root: {1}..
        /// </summary>
        internal static string OpeningThreadScope {
            get {
                return ResourceManagerStub.GetString("OpeningThreadScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistence engine configured to page every &apos;{0}&apos; records..
        /// </summary>
        internal static string PagingSpecified {
            get {
                return ResourceManagerStub.GetString("PagingSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging all stored data for bucket &apos;{0}&apos;..
        /// </summary>
        internal static string PurgingBucket {
            get {
                return ResourceManagerStub.GetString("PurgingBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging all stored data..
        /// </summary>
        internal static string PurgingStorage {
            get {
                return ResourceManagerStub.GetString("PurgingStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration of result set completed, completing associated transaction scope..
        /// </summary>
        internal static string QueryCompleted {
            get {
                return ResourceManagerStub.GetString("QueryCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception is recoverable, completing scope..
        /// </summary>
        internal static string RecoverableExceptionCompletesScope {
            get {
                return ResourceManagerStub.GetString("RecoverableExceptionCompletesScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down persistence..
        /// </summary>
        internal static string ShuttingDownPersistence {
            get {
                return ResourceManagerStub.GetString("ShuttingDownPersistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage threw exception of type &apos;{0}&apos;, wrapping and re-throwing..
        /// </summary>
        internal static string StorageThrewException {
            get {
                return ResourceManagerStub.GetString("StorageThrewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering stream ID hasher of type &apos;{0}&apos;.
        /// </summary>
        internal static string StreamIdHasherSpecified {
            get {
                return ResourceManagerStub.GetString("StreamIdHasherSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Stream ID hash function returned is null, empty or whitespace..
        /// </summary>
        internal static string StreamIdHashIsNullEmptyOrWhiteSpace {
            get {
                return ResourceManagerStub.GetString("StreamIdHashIsNullEmptyOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Stream ID hash function returned as string of invalid length. The StreamId supplied was &apos;{0}&apos;. The hash was &apos;{1}&apos;, whose length is {2}. The maxium length allowed is {3}..
        /// </summary>
        internal static string StreamIdHashTooLong {
            get {
                return ResourceManagerStub.GetString("StreamIdHashTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to streamId is null, empty, or whitespace..
        /// </summary>
        internal static string StreamIdIsNullEmptyOrWhiteSpace {
            get {
                return ResourceManagerStub.GetString("StreamIdIsNullEmptyOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participating in connection with ambient transaction scope of .
        /// </summary>
        internal static string UsingScope {
            get {
                return ResourceManagerStub.GetString("UsingScope", resourceCulture);
            }
        }
    }
}
